-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  preferred_language text,
  updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS) for profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update their own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for high scores
create table scores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  wpm float not null,
  accuracy int not null,
  language text not null,
  score int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for scores
alter table scores enable row level security;

create policy "High scores are viewable by everyone." on scores
  for select using (true);

create policy "Users can insert their own scores." on scores
  for insert with check (auth.uid() = user_id);
